routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(['verify' => true]);
Route::get('/', function () {
	return view('login.FormLogin');
});



Auth::routes();
//Admin
Route::get('/home', 'HomeController@index')->name('home')->middleware(['auth']);
Route::get('/member', 'MemberController@index')->name('member')->middleware(['auth']);
Route::get('/delete/{id}','MemberController@delete');
//

Route::get('/EditDataProject', function () {
	return view('admin.EditDataProject');
});

Route::resource('/member', 'MemberController')->middleware(['auth']);
Route::resource('/FormProject', 'ProjectController')->middleware(['auth']);
Route::resource('/DataTesting', 'DataTestingController')->middleware(['auth']);
Route::resource('/Task', 'TaskController')->middleware(['auth']);
Route::resource('/FormTest', 'TesController')->middleware(['auth']);
Route::resource('/PM', 'AdminController')->middleware(['auth']);

Route::get('/Programer', 'HomeProgramer@index')->name('Programer')->middleware(['auth']);
Route::get('/PM', 'AdminController@index')->name('PM')->middleware(['auth']);
Route::get('/QA', 'HomeQA@index')->name('QA')->middleware(['auth']);

route::get('/Task/{id_project}','TaskController@DataTask');

route::get('/Task/getDetailJson/{id}','TaskController@getDetailJson');

route::get('/Test/getDetailJson/{id}','TesController@getDetailJson');

Route::get('/logActivity', 'AdminController@logActivity');
Route::get('/PilihProject/{id_project}', 'TaskController@PilihProject');
Route::get('/PilihDataProject/{id_project}', 'AdminController@PilihDataProject');

Route::post('/ubahStatus', 'TaskController@statusUbah')->name('Task.ubahStatus');
Route::post('/ubahStatusTesting', 'TesController@statusUbah')->name('Test.ubahStatus');


Route::get('/PilihTesting/{id_project}', 'TesController@PilihTesting');
Route::get('/FormTest/{id_testing}/UbahData', 'TesController@UbahData');


Route::get('/simpanUbah', 'TesController@simpanUbah')->name('Test.simpanUbah');

Route::get('/PilihQa/{id_users}', 'ProjectController@PilihQa');
Route::get('/ProjectDetail/{id_project}', 'TaskController@ProjectDetail');

Route::get('/test', 'AdminController@Test');

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    return "Cache is cleared";
});

resources/views/admin/v_member/View_Member.blade.php
@extends('layouts.MasterAdmin')
@section('content')
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <div class="d-flex align-items-center">
                <h4 class="card-title">Form Member</h4>
                <button class="btn btn-primary btn-round ml-auto"
                    onclick="window.location.href = '{{route('member.create')}}';">
                    <i class="fa fa-plus"></i>

                </button>
            </div>
        </div>
        <div class="card-body">
            @if(session()->get('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}

            </div><br />
            @endif
            <div class="table-responsive">
                <table id="add-row" class="display table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>No </th>
                            <th>Nama</th>
                            <th>Email</th>
                            <th>Akses</th>
                            <th><center>Aksi</center></th>
                        </tr>
                    </thead>
                    
                    <tbody>
                        <?php $no = 0;?>

                        @foreach($DataMember as $DataMember )
                        <?php $no++ ;?>
                        <tr>
                            <td>{{$no }}</td>
                            <td>{{$DataMember->name}}</td>
                            <td>{{$DataMember->email}}</td>
                            <td>{{$DataMember->role}}</td>
                            <td align="center">
                                <div class="form-button-action">
                                    <button type="button" data-toggle="tooltip" class="btn btn-link btn-primary"
                                        data-original-title="Edit Project"
                                        onclick="window.location.href = '/member/{{$DataMember->id_users}}/edit';"><i
                                            class="fa fa-edit"></i>
                                    </button>
                                    <form action="{{ route('member.destroy', $DataMember->id_users)}}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button data-toggle="tooltip" title="" class="btn btn-link btn-danger"
                                            data-original-title="Remove" type="submit">
                                            <i class="fa fa-times"></i>
                                        </button>
                                    </form>
                                </div>

                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>



@endsection

resources/views/admin/v_member/addMember.blade.php
@extends('layouts.MasterAdmin')
@section('content')
<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">New Add Member</h4>
        <ul class="breadcrumbs">
            <li class="nav-home">
                <a href="#">
                    <i class="flaticon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="/FormProject">Form Project</a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="/FormProject/create">Add Member</a>
            </li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Informasi Member Yang akan di buat</div>
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />@endif
                </div>
                <div class="card-body">
                    <form method="post" action="{{ route('member.store') }}">
                        {{ csrf_field() }}
                        <div class="row">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group ">
                                        <label for="recipient-name" class="col-form-label">Nama :</label>
                                        <input id="name" placeholder="Nama Lengkap" type="text"
                                            class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                            name="name" value="{{ old('name') }}" required autofocus>
                                        @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                        @endif
                                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 pr-0">
                                    <div class="form-group ">
                                        <label for="recipient-name" class="col-form-label">No Telepon :</label>
                                        <input id="no_tlp" placeholder="Nama Lengkap" type="text" type="text"
                                            class="form-control{{ $errors->has('no_tlp') ? ' is-invalid' : '' }}"
                                            name="no_tlp" value="{{ old('no_tlp') }}" required autofocus> 
                                        @if($errors->has('no_tlp'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('no_tlp') }}</strong>
                                        </span>
                                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <label for="recipient-name" class="col-form-label">Email :</label>
                                        <input id="email" type="email" placeholder="Email"
                                            class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}"
                                            name="email" value="{{ old('email') }}" required>
                                        @if ($errors->has('email'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </span>
                                        @endif
                                        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 pr-0">
                                    <div class="form-group ">
                                        <label for="recipient-name" class="col-form-label">Password :</label>
                                        <input id="password" type="password" placeholder="Password"
                                            class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}"
                                            name="password" required>
                                        @if ($errors->has('password'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('password') }}</strong>
                                        </span>
                                        @endif
                                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <label for="recipient-name" class="col-form-label">Konfirmasi Password :</label>
                                        <input id="password-confirm" type="password" placeholder="Re Password"
                                            class="form-control" name="password_confirmation" required> <span
                                            class="glyphicon glyphicon-log-in form-control-feedback"></span> </div>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="form-group ">
                                    <label for="recipient-name" class="col-form-label">Role :</label>
                                    <select class="form-control{{ $errors->has('role') ? ' is-invalid' : '' }}"
                                        name="role" value="{{ old('role') }}">
                                        <option name="" selected> Pilih Salah Satu </option>
                                        <option name="PM"> PM </option>
                                        <option name="QA"> QA </option>
                                        <option name="Programer"> Programer </option>
                                    </select>
                                    @if ($errors->has('role'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('role') }}</strong>
                                    </span>
                                    @endif
                                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                </div>
                                <div class="modal-footer no-bd">
                                    <button type="submit" class="btn btn-primary">Simpan</button>
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @endsection

resources/views/admin/v_member/editMember.blade.php
@extends('layouts.MasterAdmin')
@section('content')
<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">Edit Member</h4>
        <ul class="breadcrumbs">
            <li class="nav-home">
                <a href="#">
                    <i class="flaticon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="/FormProject">Form Project</a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="/member/{{$Data->id_users}}/edit">Edit Member</a>
            </li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Informasi Member Yang akan di Edit</div>
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />@endif
                </div>
                <div class="card-body">
                    <form method="post" action="{{ route('member.store') }}">
                        {{ csrf_field() }}
                        <div class="row">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group ">
                                        <label for="recipient-name" class="col-form-label">Nama :</label>
                                        <input id="name" value="{{ $Data->name }}" placeholder="Nama Lengkap" type="text"
                                            class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                            name="name" value="{{ old('name') }}" required autofocus>
                                        @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                        @endif
                                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 pr-0">
                                    <div class="form-group ">
                                        <label for="recipient-name" class="col-form-label">No Telepon :</label>
                                        <input id="no_tlp" value="{{ $Data->no_tlp }}" placeholder="Nama Lengkap" type="text" type="text"
                                            class="form-control{{ $errors->has('no_tlp') ? ' is-invalid' : '' }}"
                                            name="no_tlp" value="{{ old('no_tlp') }}" required autofocus> 
                                        @if($errors->has('no_tlp'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('no_tlp') }}</strong>
                                        </span>
                                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <label for="recipient-name" class="col-form-label">Email :</label>
                                        <input id="email" value="{{ $Data->email }}" type="email" placeholder="Email"
                                            class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}"
                                            name="email" value="{{ old('email') }}" required>
                                        @if ($errors->has('email'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </span>
                                        @endif
                                        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 pr-0">
                                    <div class="form-group ">
                                        <label for="recipient-name" class="col-form-label">Password :</label>
                                        <input id="password" value="{{ $Data->password }}"  type="password" placeholder="Password"
                                            class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}"
                                            name="password" required>
                                        @if ($errors->has('password'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('password') }}</strong>
                                        </span>
                                        @endif
                                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <label for="recipient-name" class="col-form-label">Konfirmasi Password :</label>
                                        <input id="password-confirm" type="password" placeholder="Re Password"
                                            class="form-control" name="password_confirmation" required> <span
                                            class="glyphicon glyphicon-log-in form-control-feedback"></span> </div>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="form-group ">
                                    <label for="recipient-name" class="col-form-label">Role :</label>
                                    <select class="form-control{{ $errors->has('role') ? ' is-invalid' : '' }}"
                                        name="role" value="{{ old('role') }}">
                                        <option name=""> Pilih Salah Satu </option>
                                        <option <?php if ($Data->role == "PM" ) echo 'selected' ; ?> name="PM"> PM </option>
                                        <option <?php if ($Data->role == "QA" ) echo 'selected' ; ?> name="QA" > QA </option>
                                        <option <?php if ($Data->role == "Programer" ) echo 'selected' ; ?> name="Programer"> Programer </option>
                                    </select>
                                    @if ($errors->has('role'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('role') }}</strong>
                                    </span>
                                    @endif
                                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                </div>
                                <div class="modal-footer no-bd">
                                    <button type="submit" class="btn btn-primary">Simpan</button>
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @endsection