routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(['verify' => true]);
Route::get('/', function () {
	return view('login.FormLogin');
});



Auth::routes();
//Admin
Route::get('/home', 'HomeController@index')->name('home')->middleware(['auth']);
Route::get('/member', 'MemberController@index')->name('member')->middleware(['auth']);
Route::get('/delete/{id}','MemberController@delete');
//

Route::get('/EditDataProject', function () {
	return view('admin.EditDataProject');
});

Route::resource('/member', 'MemberController')->middleware(['auth']);
Route::resource('/FormProject', 'ProjectController')->middleware(['auth']);
Route::resource('/DataTesting', 'DataTestingController')->middleware(['auth']);
Route::resource('/Task', 'TaskController')->middleware(['auth']);
Route::resource('/FormTest', 'TesController')->middleware(['auth']);
Route::resource('/PM', 'AdminController')->middleware(['auth']);

Route::get('/Programer', 'HomeProgramer@index')->name('Programer')->middleware(['auth']);
Route::get('/PM', 'AdminController@index')->name('PM')->middleware(['auth']);
Route::get('/QA', 'HomeQA@index')->name('QA')->middleware(['auth']);

route::get('/Task/{id_project}','TaskController@DataTask');

route::get('/Task/getDetailJson/{id}','TaskController@getDetailJson');

route::get('/Test/getDetailJson/{id}','TesController@getDetailJson');

Route::get('/logActivity', 'AdminController@logActivity');
Route::get('/PilihProject/{id_project}', 'TaskController@PilihProject');
Route::get('/PilihDataProject/{id_project}', 'AdminController@PilihDataProject');

Route::post('/ubahStatus', 'TaskController@statusUbah')->name('Task.ubahStatus');
Route::post('/ubahStatusTesting', 'TesController@statusUbah')->name('Test.ubahStatus');


Route::get('/PilihTesting/{id_project}', 'TesController@PilihTesting');
Route::get('/FormTest/{id_testing}/UbahData', 'TesController@UbahData');


Route::get('/simpanUbah', 'TesController@simpanUbah')->name('Test.simpanUbah');

Route::get('/PilihQa/{id_users}', 'ProjectController@PilihQa');
Route::get('/ProjectDetail/{id_project}', 'TaskController@ProjectDetail');

Route::get('/test', 'AdminController@Test');

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    return "Cache is cleared";
});

resources/views/Programer/View_Test.blade.php
@extends('layouts.MasterProgramer')
@section('content')
@include('sweet::alert')
<div class="row mt--2">
    <div class="col-md-12">
        <div class="card full-height">
            <div class="card-body">
            @if(session()->get('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div><br />
            @endif
                <div class="card-title">Pilih Task yang akan di tampilkan</div>
                <div class="card-category"></div>
                <select class="form-control" name="id_project" id="PilidData">
                    <option value="">Pilih Data Task</option>
                    @foreach($DataTest as $DataTest )
                    <option value="{{ $DataTest->id_testing }}">{{ $DataTest->nama_project }} - {{ $DataTest->nama_test }} - {{ $DataTest->jenis_test }} </option>
                    @endforeach
                </select>
            </div>
        </div>
    </div>
    </div>
 
    <div class="row mt--6">
        <div class="col-md-12">
            <div id="TampilData"> </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $('#PilidData').on('change',function () {
                
                var id = $(this).val();
                $.ajax({
                    type: 'GET',
                    url: "/PilihTesting/"+id,
                    success: function (respons) {
                        console.log(respons);
                        $('#TampilData').html("");

                        $.each(respons,function (index,element) {
                            var status_testing = '';
                                if (element.status_testing == 'OnProgres') {
                                    cetakstatus = '<span class="colorinput-color bg-primary"  data-toggle="tooltip"  data-original-title="On Progres" class="colorinput-input"> <center style=" margin-top: 5px;"> O </center>';
                                }else if (element.status_testing == 'Testing') {
                                    cetakstatus = '<span class="colorinput-color bg-info"  data-toggle="tooltip"  data-original-title="Testing" class="colorinput-input"><center style=" margin-top: 5px;"> T </center>';
                                }else  if (element.status_testing == 'ReadyToTes') {
                                    cetakstatus = '<span class="colorinput-color bg-secondary"  data-toggle="tooltip"  data-original-title="Ready To Tes" class="colorinput-input"><center style=" margin-top: 5px;"> R </center>';
                                }else  if (element.status_testing == 'Issue') {
                                    cetakstatus = '<span class="colorinput-color bg-success"  data-toggle="tooltip"  data-original-title="Issue" class="colorinput-input"><center style=" margin-top: 5px;"> I </center>';
                                }else  if (element.status_testing == 'Solved') {
                                    cetakstatus = '<span class="colorinput-color bg-warning" data-toggle="tooltip"  data-original-title="Sloved" class="colorinput-input"><center style=" margin-top: 5px;"> S </center>';
                                }else  if (element.status_testing == 'Closed') {
                                    cetakstatus = '<span class="colorinput-color bg-danger" data-toggle="tooltip"  data-original-title="Closed" class="colorinput-input"><center style=" margin-top: 5px;"> C </center></span>';
                                }
                            $('#TampilData').append(`
                            
                            
                                    <div class="card full-height">
                                        <div class="card-body">
                                        <div class="card-header">
                                                <div class="d-flex align-items-center">
                                                    <h4 class="card-title">`+element.nama_task+`</h4>
                                                    <button class="btn btn-primary btn-round ml-auto"
                                                        onclick="window.location.href = '/FormTest/`+element.id_testing+`/edit';">
                                                        <i class="fa fa-check"></i>

                                                    </button>
                                                </div>
                                            </div>
                                            <div class="card-category"></div>
                                            <div class="d-flex flex-wrap justify-content-around pb-2 pt-2">
                                                <table class="display table table-striped table-hover">
                                                    <tr>
                                                        <td>Kode Testing</td>
                                                        <td>Nama Tes</td>
                                                        <td>Jenis Tes</td>
                                                        <td colspan='2'><center>Status</center></td>
                                                        <td></td>
                                                    </tr>
                                                    <tr>
                                                        <td>TST-0`+element.id_testing+`</td>
                                                        <td>`+element.nama_test+`</td>
                                                        <td>`+element.jenis_test+`</td>
                                                        <td colspan='2'>`+element.status_testing+`</td>
                                                        <td> `+cetakstatus+`</td>
                                                       
                                                        </td>
                                                    </tr>
                                                </table>
                                            </div>
                                        </div>
                                    </div>

                                    
                             

                            `);
                        });
                    },
                    error: function (e,log) {
                        // DO SOMETHING WHEN ERROR
                    }
                });                
                
            })
        })
    </script>
@endsection

resources/views/Programer/editTest.blade.php
@extends('layouts.MasterProgramer')
@section('content')
@include('sweet::alert')
<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">Applay Project</h4>
        <ul class="breadcrumbs">
            <li class="nav-home">
                <a href="#">
                    <i class="flaticon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="/FormTest">Task Project</a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="/Task/create">Apllay New Task</a>
            </li>
        </ul>
    </div>

 
                                             
                        

        <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Test Yang Akan Dibuat</div>
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />@endif
                </div>
                <form method="post" action="{{ route('FormTest.update', $DataTesting[0]->id_testing) }}">
                    @method('PATCH')
                    @csrf
                <div class="card-body">                               
                        <div class="row">
                                <div class="col-md-6 pr-0">
                                    <div class="form-group ">
                                    <label for="recipient-name" class="col-form-label">Nama Test :</label>
                                    <input type="hidden" name="no_qa" value="{{$DataTesting[0]->no_qa}}" readonly class=" form-control">
                                    <!-- <input type="text" name="status2" value="{{$DataTesting[0]->status}}" readonly class=" form-control"> -->
                                    <input type="hidden" name="id_task" value="{{$DataTesting[0]->id_task}}" readonly class=" form-control">
                                    <input type="hidden" name="id_project" value="{{$DataTesting[0]->id_project}}" readonly class=" form-control">
                                    <input type="hidden" name="id_ussers" value="{{$DataTesting[0]->id_ussers}}" readonly class=" form-control">
                                    <input type="hidden" name="nama_project" value="{{$DataTesting[0]->nama_project}}" readonly class=" form-control">
                                    
                                    
                                        <input type="text" name="nama_test" value="{{$DataTesting[0]->nama_task}}" readonly class=" form-control">
                                        @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                        @endif
                                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                    </div>
                                </div>
                            
                               
                                <div class="col-md-6 pr-0">
                                    <div class="form-group ">
                                    <label for="recipient-name" class="col-form-label">Jenis Test :</label>
                                    <input type="text" name="jenis_test" value="{{$DataTesting[0]->jenis_test}}" readonly class=" form-control">

                                        @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('jenis_test') }}</strong>
                                        </span>
                                        @endif
                                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                    </div>
                                </div>


                               
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <label for="recipient-name" class="col-form-label">Status</label>
                                        <div class="row gutters-xs">
													<div class="col-auto">
														<label class="colorinput">
															<input name="status_testing" type="checkbox" value="OnProgres" <?php if ($DataTesting[0]->status_testing == 'OnProgres' ){echo 'checked';} ?>
                                                            data-toggle="tooltip"  data-original-title="On Progres" class="colorinput-input">
															<span class="colorinput-color bg-primary"></span>
														</label>
													</div>
													<div class="col-auto">
														<label class="colorinput">
															<input name="status_testing" type="checkbox" value="ReadyToTes" <?php if ($DataTesting[0]->status_testing == 'ReadyToTes' ){echo 'checked';} ?>  
                                                            data-toggle="tooltip"  data-original-title="Ready To Tes" class="colorinput-input">
															<span class="colorinput-color bg-secondary"></span>
														</label>
													</div>
													<div class="col-auto">
														<label class="colorinput">
															<input name="status_testing" type="checkbox" value="Testing" <?php if ($DataTesting[0]->status_testing == 'Testing' ){echo 'checked';} ?>  
                                                            data-toggle="tooltip"  data-original-title="Testing" value="info" class="colorinput-input">
															<span class="colorinput-color bg-info"></span>
														</label>
													</div>
													<div class="col-auto">
														<label class="colorinput">
															<input name="status_testing" type="checkbox" value="Issue"  <?php if ($DataTesting[0]->status_testing == 'Issue' ){echo 'checked';} ?>  
                                                            data-toggle="tooltip"  data-original-title="Issue" value="success" class="colorinput-input">
															<span class="colorinput-color bg-success"></span>
														</label>
													</div>
													<div class="col-auto">
														<label class="colorinput">
															<input name="status_testing" type="checkbox" value="Closed"  <?php if ($DataTesting[0]->status_testing == 'Closed' ){echo 'checked';} ?>   
                                                            data-toggle="tooltip"  data-original-title="Closed" class="colorinput-input">
															<span class="colorinput-color bg-danger"></span>
														</label>
													</div>
													<div class="col-auto">
														<label class="colorinput">
															<input name="status_testing" type="checkbox"  value="Solved" <?php if ($DataTesting[0]->status_testing == 'Solved' ){echo 'checked';} ?> 
                                                             data-toggle="tooltip"  data-original-title="Solved" class="colorinput-input">
															<span class="colorinput-color bg-warning"></span>
														</label>
													</div>
												</div>
                                        @if ($errors->has('nama_task'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('nama_task') }}</strong>
                                        </span>
                                        @endif
                                        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                                    </div>
                                </div>
                                
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <label for="recipient-name" class="col-form-label">Nama Developer</label>
                                        <input type="text" name="nama_developer" value="{{$DataTesting[0]->name}}" readonly class=" form-control">
                                        @if ($errors->has('nama_task'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('nama_task') }}</strong>
                                        </span>
                                        @endif
                                        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                                    </div>
                                </div>

                               
                               
                            </div>
                           
                        </div>              
               </div>
            </div>
        </div>
        <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Test Yang Akan Dibuat</div>
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />@endif
                </div>
                <div class="col-md-12 pr-0">
                                    <div class="form-group ">
                                    <label for="recipient-name" class="col-form-label">Keterangan :</label>
                                    {!! html_entity_decode($DataTesting[0]->keterangan_test) !!}
                                    @if ($errors->has('role'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('role') }}</strong>
                                    </span>
                                    @endif
                                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary btn-lg btn-block">Simpan</button>
            </div>
            
        </div>
        </div>
    </form>
                 

    @endsection